version: '3.8'
services:
  mysql:
    image: mysql:8.0
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
      MYSQL_USER: todouser
      MYSQL_PASSWORD: password
    restart: always
  todo:
    build:
      context: .
      dockerfile: ./cmd/todo/Dockerfile
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - mysql
